export const ALL_PROBLEMS_REQUEST = "ALL_PROBLEMS_REQUEST";
export const ALL_PROBLEMS_SUCCESS = "ALL_PROBLEMS_SUCCESS";
export const ALL_PROBLEMS_FAILURE = "ALL_PROBLEMS_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const POST_PROBLEM_REQUEST = "POST_PROBLEM_REQUEST";
export const POST_PROBLEM_SUCCESS = "POST_PROBLEM_SUCCESS";
export const POST_PROBLEM_FAILURE = "POST_PROBLEM_FAILURE";
